name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    # Add database service
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dbPassword1234
          POSTGRES_DB: ipss_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: npm install and migrate up
        run: |
          npm install
          npm run prisma:db:migrate
          npm run prisma:db:seed
          npm run test

        env:
          CI: true
          DATABASE_URL: "postgresql://postgres:dbPassword1234@localhost:5432/ipss_test"
          APP_LANGUAGE: "en"
          JWT_ACCESS_TOKEN_SECRET: "jwt_secret_test"
          JWT_REFRESH_TOKEN_SECRET: "jwt_refresh_secret_test"

